[profile.default]
src = 'src'
out = 'out'
libs = ['_imagine', 'node_modules', 'script']
solc_version = '0.8.17'
optimizer = true
optimizer_runs = 5000
via_ir = true
fs_permissions = [{ access = "read", path = "./addresses"}, { access = "read", path = "./chainConfigs"}, { access = "read", path = "./package.json" }]

[profile.optimized]
optimizer = true
optimizer_runs = 5000
out = 'out'
script = 'src'
solc_version = '0.8.17'
src = 'src'
test = 'src'
via_ir = true

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
goerli = "https://eth-goerli.g.alchemy.com/v2/${ALCHEMY_KEY}"
# for optimism, since we are just using this for deployment/fork testing,
# we can use these since they're lower volume.
optimism = "https://mainnet.optimism.io"
optimism_goerli = "https://goerli.optimism.io"
zora = "https://rpc.zora.energy"
zora_goerli = "https://testnet.rpc.zora.energy"
base_goerli = "https://goerli.base.org"
base = "https://developer-access-mainnet.base.org"
pgn_sepolia = "https://sepolia.publicgoods.network"
pgn = "https://rpc.publicgoods.network"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
