on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string

env:
  # Setting an environment variable with the value of a configuration variable
  package_folder: packages/${{ inputs.package }}

jobs:
  build:
    name: Build and cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node deps and founry
        uses: ./.github/actions/setup_deps

      - name: Build contracts
        run: |
          cd $package_folder && forge build

      - name: Archive built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: foundry-built-artifacts
          path: |
            ${package_folder}/cache
            ${package_folder}/out
          retention-days: 1

  contract_size_check:
    needs: build
    strategy:
      fail-fast: true

    name: Contract Size Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node deps and founry
        uses: ./.github/actions/setup_deps

      - name: Download foundry artifacts
        uses: actions/download-artifact@v3
        with:
          name: foundry-built-artifacts

      - name: Check contract sizes
        run: |
          cd $package_folder && forge build --sizes

  test:
    needs: build
    strategy:
      fail-fast: true

    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node deps and founry
        uses: ./.github/actions/setup_deps

      - name: Download foundry artifacts
        uses: actions/download-artifact@v3
        with:
          name: foundry-built-artifacts

      - name: Run Forge tests
        run: |
          cd $package_folder && forge test -vvv

  test_fork:
    needs: build
    strategy:
      fail-fast: true

    name: Fork Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node deps and founry
        uses: ./.github/actions/setup_deps

      - name: Download foundry artifacts
        uses: actions/download-artifact@v3
        with:
          name: foundry-built-artifacts

      - name: Run fork tests
        run: |
          cd $package_folder && forge test -vvv --match-test fork
        env:
          FORK_TEST_CHAINS: mainnet,goerli,optimism,optimism_goerli,zora,zora_goerli,base_goerli,base
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}

  storage_layout:
    needs: build
    strategy:
      fail-fast: true

    name: Inpect storage layout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node deps and founry
        uses: ./.github/actions/setup_deps

      - name: Download foundry artifacts
        uses: actions/download-artifact@v3
        with:
          name: foundry-built-artifacts

      - name: "Inspect Storage Layout"
        continue-on-error: false
        run: cd $package_folder && yarn run storage-inspect:check

  build_js:
    needs: build
    strategy:
      fail-fast: true

    name: Build JS Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node deps and founry
        uses: ./.github/actions/setup_deps

      - name: Download foundry artifacts
        uses: actions/download-artifact@v3
        with:
          name: foundry-built-artifacts

      - name: Build js package
        run: |
          cd $package_folder && yarn prepack
